### PR TITLE
GDM-220: add registry system for tabs in the manager panel. Canvas eleme...

### PR DESCRIPTION
**Pull request by janvenstermans**
...nts that will be added, might not be instantiable on module load. Therefore, two different implementations of ManagerTabData are provided.

### CODE REVIEW

**Comment by janvenstermans** [comment]
test at http://dev.geomajas.org/sleevemonkey-example-GDM-220_SMK-137_registryManagerTabs/

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by hkristof** [comment]
Kristof: +1 (binding)

= _ =

**Comment by janvenstermans** [comment]
Vote successful:
Oliver May: +1 (binding)
Kristof: +1 (binding) = _ =

Jan Venstermans: +1

**Pull request merged**
