### PR TITLE
GDM-214: update groupId and artefactIds

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by hkristof** [comment]
Kristof: +1 (binding) 
= _ =

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by janvenstermans** [comment]
Vote Successful
Oliver May: +1 (binding)
Kristof: +1 (binding) = _ =

Jan Venstermans: +1

**Pull request merged**
