### PR TITLE
GDM-221: make new window open in new tab in IE11. Others browsers should...

### PR DESCRIPTION
**Pull request by janvenstermans**
... (stay) do the same

BUGFIX

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by janvenstermans** [comment]
test at http://dev.geomajas.org/sleevemonkey-example-GDM-221_SMK-137_IEopenDeskInTab/

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Bugfix vote successful:
Oliver May: +1 (binding)
Jan Venstermans: +1

**Pull request merged**
