### PR TITLE
Gdm 187 remove user section

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
+1 (binding)

**Comment by hkristof** [comment]
Kristof: +1 (binding) 
= _ =

**Comment by janvenstermans** [comment]
Vote Successful:
Oliver May: +1 (binding)
Kristof: +1 (binding) = _ =

Jan Venstermans: +1

**Comment by janvenstermans** [comment]
cherry picked commits to master, "mvn clean install" successful locally, pushed to remote

**Pull request closed without merging**
