### PR TITLE
GDM-208: attributes grid: improve selection of non-select checkboxes

### PR DESCRIPTION
**Pull request by janvenstermans**

### CODE REVIEW

**Comment by janvenstermans** [comment]
example at http://dev.geomajas.org/sleevemonkey-example-GDM-208_SMK-121_shpWfsAttributeGridCheckboxes/manager/

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
bug fix vote successful
Oliver May: +1 (binding)
Jan Venstermans: +1

**Pull request merged**
